export const WAFFLES_RECEIVER = process.env.NEXT_PUBLIC_RECEIVER_ADDRESS!; // EOA receiving funds
export const USDC_ADDRESS = process.env.NEXT_PUBLIC_USDC_ADDRESS!; // Base USDC token address
export const LEADERBOARD_PAGE_SIZE = 25;
export const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
export const SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;

export const BASE_ACCOUNT_ADDRESS =
  process.env.NEXT_PUBLIC_BASE_ACCOUNT_ADDRESS!;
export const FARCASTER_HEADER = process.env.NEXT_PUBLIC_FARCASTER_HEADER!;
export const FARCASTER_PAYLOAD = process.env.NEXT_PUBLIC_FARCASTER_PAYLOAD!;
export const FARCASTER_SIGNATURE = process.env.NEXT_PUBLIC_FARCASTER_SIGNATURE!;

export const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL!;
export const FARCASTER_URL = process.env.NEXT_PUBLIC_FARCASTER_URL!;
export const FARCASTER_ICON_URL = process.env.NEXT_PUBLIC_FARCASTER_ICON_URL!;
export const FARCASTER_SPLASH_IMAGE_URL =
  process.env.NEXT_PUBLIC_FARCASTER_SPLASH_IMAGE_URL!;
export const FARCASTER_SPLASH_BACKGROUND_COLOR =
  process.env.NEXT_PUBLIC_FARCASTER_SPLASH_BACKGROUND_COLOR!;
export const FARCASTER_WEBHOOK_URL =
  process.env.NEXT_PUBLIC_FARCASTER_WEBHOOK_URL!;
export const FARCASTER_SUBTITLE = process.env.NEXT_PUBLIC_FARCASTER_SUBTITLE!;
export const FARCASTER_DESCRIPTION =
  process.env.NEXT_PUBLIC_FARCASTER_DESCRIPTION!;
export const FARCASTER_SCREENSHOT_URLS =
  process.env.NEXT_PUBLIC_FARCASTER_SCREENSHOT_URLS!;
export const FARCASTER_PRIMARY_CATEGORY =
  process.env.NEXT_PUBLIC_FARCASTER_PRIMARY_CATEGORY!;
export const FARCASTER_TAGS = process.env.NEXT_PUBLIC_FARCASTER_TAGS!;
export const FARCASTER_HERO_IMAGE_URL =
  process.env.NEXT_PUBLIC_FARCASTER_HERO_IMAGE_URL!;
export const FARCASTER_TAGLINE = process.env.NEXT_PUBLIC_FARCASTER_TAGLINE!;
